export const commands = [
  'put <pri> <delay> <ttr> <bytes>\r\n<data>\r\n',
  'use <tube>\r\n',
  'reserve\r\n',
  'reserve-with-timeout <seconds>\r\n',
  'delete <id>\r\n',
  'release <id> <pri> <delay>\r\n',
  'bury <id> <pri>\r\n',
  'touch <id>\r\n',
  'watch <tube>\r\n',
  'ignore <tube>\r\n',
  'peek <id>\r\n',
  'peek-ready\r\n',
  'peek-delayed\r\n',
  'peek-buried\r\n',
  'kick <bound>\r\n',
  'kick-job <id>\r\n',
  'stats-job <id>\r\n',
  'stats-tube <tube>\r\n',
  'stats\r\n',
  'list-tubes\r\n',
  'list-tube-used\r\n',
  'list-tubes-watched\r\n',
  'quit\r\n',
  'pause-tube <tube> <delay>\r\n'
];

export const replies = [
  'INSERTED <id>\r\n',
  'BURIED <id>\r\n',
  'EXPECTED_CRLF\r\n',
  'JOB_TOO_BIG\r\n',
  'DRAINING\r\n',
  'USING <tube>\r\n',
  'RESERVED <id> <bytes>\r\n<data>\r\n',
  'FOUND <id> <bytes>\r\n<data>\r\n',
  'DEADLINE_SOON\r\n',
  'TIMED_OUT\r\n',
  'DELETED\r\n',
  'NOT_FOUND\r\n',
  'RELEASED\r\n',
  'BURIED\r\n',
  'TOUCHED\r\n',
  'WATCHING <count>\r\n',
  'KICKED\r\n',
  'KICKED <count>\r\n',
  'OK <bytes>\r\n<data>\r\n',
  'PAUSED\r\n'
];

export const types = {
  pri: Number,
  delay: Number,
  ttr: Number,
  bytes: Number,
  data: Buffer,
  id: Number,
  tube: String,
  bound: Number,
  seconds: Number,
  count: Number
};
